### ISSUE TITLE
Same IDs

### ISSUE THREAD

**Issue by Amerlander** [metonym/svelte-typeahead#10]
The outer `div`, the `form` and the `input`  are all sharing the same id. Is this by intention? 
https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L104
https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L113

I was also wondering about the double writing of `on:focus` and `on:clear`:
https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L118
https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L122

But I feel like this is by intention and I just didn't get the concept behind it, so maybe this issue can just be closed.

**Comment by metonym** [comment]
> The outer `div`, the `form` and the `input` are all sharing the same id. Is this by intention?
> https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L104
> 
> 
> https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L113

Hmm. Yes, it seems like `Search` should not have the same id.

> I was also wondering about the double writing of `on:focus` and `on:clear`:
> https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L118
> 



> https://github.com/metonym/svelte-typeahead/blob/9c2eb8e949b9b43dc1b4c7d9eba7025856210dd4/src/Typeahead.svelte#L122
> 
> But I feel like this is by intention and I just didn't get the concept behind it, so maybe this issue can just be closed.

This is required to forward the events to the Search component.
