### ISSUE TITLE
Focus after select not focusing

### ISSUE THREAD

**Issue by Amerlander** [metonym/svelte-typeahead#11]
When I do `focusAfterSelect='true'` the search results stay open after an selection, but the input doesn't get focus. I have to select it with the mouse to change the text in it.
The console error says `TypeError: searchRef.focus is not a function`. 

I wasnt able to get the input focused, but the error message can be removed by changing

```
    if (focusAfterSelect) searchRef.focus();

    hideDropdown = true;
```
    
 to 

```
        if (!focusAfterSelect)   hideDropdown = true;
```

**Comment by metonym** [comment]
This one's on me. A breaking change in `svelte-search` was to remove the [exported `focus` function](https://github.com/metonym/svelte-search/commit/5208c59da3a603152e7733d4bcc98444d11a1f41#diff-df60c8c7d56c4d6b0731e034ca2d76595f9199e4dd95372046167fbfa4f7c0acL12) in favor of binding to `ref`.

I think the fix would be to bind to the `ref` prop and perform a null check before focusing the input element.

```diff
<Search
    {...$$restProps}
-  bind:this={searchRef}
+  bind:ref={searchRef}
```

**Comment by Amerlander** [comment]
When focus after select enabled the hide dropdown should not be called:
    ```
    if (focusAfterSelect) {
      searchRef.focus();
    } else {
      hideDropdown = true;
    }
    ```
    
   Before the fix it wasn`t called because the `searchRef.focus()` failed and stopped further execution.
   Or was this a bug and the intention is to close the result list even when focus is keept?

**Comment by metonym** [comment]
Yes, it's intentional to hide the dropdown after selecting or a result or blurring the input.

**Comment by Amerlander** [comment]
But with getting the input focused again it should open again (or just not got closed).

Now when having `focusAfterSelect='true'` and selecting an item the input focuses, but the result list does not show up.
Clicking in the input again will not open the results what I would expect as a user, since the input is already focused.

**Comment by Amerlander** [comment]
Maybe just changing the order would be the solution. Then all events will get called and the resultset will stay open as expected:

     hideDropdown = true;
    if (focusAfterSelect)  searchRef.focus();

**Comment by metonym** [comment]
from a UX perspective, Id prefer the dropdown to be closed after searching and selecting a result.

**Comment by Amerlander** [comment]
I totally agree when `inputAfterSelect` is set to `clear` or `update` - in the first case the result set will autoclose, in the other case the result set will be equal to the selected item and it doesn't make much sense. 

I understood Typeahead more as a search, than an input field, what was the reason for introducing `keep` for me.
In that combination it feels pretty much like a bug, when the results are closing and cant be opened by focusing the input.

Here is a sample with `inputAfterSelect` set to true and `focusAfterSelect` also true. This behaviour would be 100% of my expectations, when the input field would not keepits focus (like the default behaviour):

https://user-images.githubusercontent.com/3764089/108629379-ece3cf80-745f-11eb-8554-8fe71789794d.mp4

Compared to:

https://user-images.githubusercontent.com/3764089/108629386-f3724700-745f-11eb-8967-c1b7dbfcaabb.mp4

The video is made on the code of this pr without the user styling applied: https://github.com/metonym/svelte-typeahead/pull/13

**Comment by Amerlander** [comment]
Since I can do `this.focus();` in the `on:select` function I could live without having this changed, but I believe it feels more convenient in most cases and the name also implies, that the focus is set back *after* the selection, which implies, that the focus get lost while selecting and returned back after everything else. Which for me involves opening the results when there is an input.
