### ISSUE TITLE
Limit the number of matching items?

### ISSUE THREAD

**Issue by PlkMarudny** [metonym/svelte-typeahead#16]
Is there any way to limit the number of returned matches, to 10 for example?

**Comment by metonym** [comment]
Released in v2.4.0

Specify the maximum number of results [using the `limit` prop](https://github.com/metonym/svelte-typeahead#limit-the-number-of-results). The default value if `Infinity`.

```svelte
<Typeahead limit={2} {data} {extract} />
```

**Comment by PlkMarudny** [comment]
Indeed, it works @2.4.0, apparently did not @2.3.0, thank  you very much.
