### ISSUE TITLE
Is this importing svelte-search two times?

### ISSUE THREAD

**Issue by frederikhors** [metonym/svelte-typeahead#24]
I'm using this amazing component in a `"@sveltejs/kit": "1.0.0-next.142"`.

Analyzing with `source-map-explorer` I found that `svelte-typeahead` is ~7KB but there is `svelte-search` too ~4KB.

<img width="454" alt="Screenshot 2021-08-09 at 21 08 55" src="https://user-images.githubusercontent.com/41120635/128760872-b53357de-df9e-4484-b0ed-e1ccaec4e5e3.png">

![image](https://user-images.githubusercontent.com/41120635/128761075-6b160bc9-2cfa-4ff4-93ab-cf8b123b6ae4.png)

Is this correct?

**Or am I importing `svelte-search` two times?**

**Comment by metonym** [comment]
This is correct. `svelte-typeahead` depends on `svelte-search` and `fuzzy`.

**Comment by frederikhors** [comment]
Thanks.
