### ISSUE TITLE
Debounce is not working...

### ISSUE THREAD

**Issue by frederikhors** [metonym/svelte-typeahead#25]
REPL: https://svelte.dev/repl/6123712226fa458c87064d891b91cbbd?version=3.42.1

If you see the console you'll notice the `value` is changed immediately, not after 2000 ms.

Am I wrong?

**Comment by frederikhors** [comment]
It works in `svelte-search`: https://svelte.dev/repl/e8f99b1aca71441c9866f71ff76ff868?version=3.42.1.

I think the problem the use of `afterUpdate` here: https://github.com/metonym/svelte-search/blob/master/src/Search.svelte#L38

Don't you think, @metonym?

**Comment by metonym** [comment]
You're correct in that `debounce` has no effect on `value`. It does debounce the dispatched `on:type` event, though.

In the following example, the value from `console.log(e.detail)` will be debounced by 2 seconds.

```svelte
<script>
  import Typeahead from "svelte-typeahead";

  const data = [
    { id: 0, state: "California" },
    { id: 1, state: "North Carolina" },
    { id: 2, state: "North Dakota" },
    { id: 3, state: "South Carolina" },
    { id: 4, state: "South Dakota" },
    { id: 5, state: "Michigan" },
    { id: 6, state: "Tennessee" },
    { id: 7, state: "Nevada" },
    { id: 8, state: "New Hampshire" },
    { id: 9, state: "New Jersey" },
  ];

  const extract = (item) => item.state;
</script>

<Typeahead
  {data}
  {extract}
  debounce={2000}
  on:type={(e) => console.log(e.detail)}
/>
```

The intention of this component is to be used client-side. It presumes that the search data is small enough to still be performant in-memory. I feel that server-side search is out of scope, and is better handled by full text search engines. I believe you alluded to this in #28.
