### ISSUE TITLE
Should we communicate no results?

### ISSUE THREAD

**Issue by frederikhors** [metonym/svelte-typeahead#27]
I think we should somehow communicate to the user that we have not found any results for their search.

Now the list disappears and neither happens nor is any message displayed.

What do you think?

**Comment by metonym** [comment]
<Typeahead value="abcd" {data} {extract} let:value>
  <svelte:fragment slot="no-results">
    No results found for "{value}"
  </svelte:fragment>
</Typeahead>

**Comment by xpluscal** [comment]
Is there a way to get the current possible results in javascript?

**Comment by xpluscal** [comment]
Aka given the user has input data, how would one get the available results?
