### ISSUE TITLE
How to set initial value?

### ISSUE THREAD

**Issue by Gildedter** [metonym/svelte-typeahead#46]
If I want to pass in a key and have that be the selected one from my `data` as an initial value, then upon edit I just erase it, is it possible with this component?

**Comment by metonym** [comment]
You can set an initial value using the `value` prop which will be used to search and display any matching results.

```svelte
<Typeahead value="initial value" {data} {extract} />
```

**Comment by Gildedter** [comment]
it sometimes shows the dropdown result, I'm ignoring it for now,
