### ISSUE TITLE
Z-index fix?

### ISSUE THREAD

**Issue by Gildedter** [metonym/svelte-typeahead#47]
I currently have multiples of this component instanced and... just look at this:

![image](https://user-images.githubusercontent.com/93777256/176082541-6e32bbaf-d8cf-4aa5-9fe2-fe2291124140.png)

the ones below are also instances of `svelte-type-ahead`, the results of the focused instance are rendered under the instances below them, any work around for this?

**Comment by metonym** [comment]
In reference to https://github.com/metonym/svelte-typeahead/issues/46#issuecomment-1168097926, I think we can adopt a two-birds-one-stone approach and add a prop that only shows the dropdown menu when the input is focused.

**Comment by Gildedter** [comment]
I think that would solve https://github.com/metonym/svelte-typeahead/issues/46#issuecomment-1168097926, but not the z-index of the drop down when focused, on my screenshot the dropdown list is rendered below the other instances of `svelte-typeahead`

**Comment by metonym** [comment]
Fixed in [v4.2.4](https://github.com/metonym/svelte-typeahead/releases/tag/v4.2.4).
