### ISSUE TITLE
[Q] How to pre-select a value without the dropdown showing?

### ISSUE THREAD

**Issue by dominikus** [metonym/svelte-typeahead#54]
Hi all,

is it possible to pre-select a value on mount without the dropdown showing?

I'm binding a `value` variable to the component which I set to an item from the `data` array on mount. The value shows up in the search box (good!), but unfortunately the dropdown is open as well, showing exactly one result (not so good!):

![image](https://user-images.githubusercontent.com/110566/187160015-89fd8170-0cdc-464f-8bf1-586a0f774b1d.png)

Is there any way to prevent this from happening?

```
// rough code:
let value = 'UNITED STATES';
...
<Typeahead autoselect data={countries} {extract} bind:value />
```

**Comment by metonym** [comment]
This is supported in [v4.3.0](https://github.com/metonym/svelte-typeahead/releases/tag/v4.3.0).

Set `showDropdownOnFocus` to `true` for the results dropdown to only be shown if the search input is focused. I believe this addresses your use case where an initial value is desired without obtrusively showing the dropdown.

[Svelte REPL](https://svelte.dev/repl/9532173b1cf1445e92cf2309ad3c7337?version=3.49.0)

```svelte
<Typeahead value="ca" showDropdownOnFocus {data} {extract} />
```
