### ISSUE TITLE
[QUESTION] Show first entries on input click

### ISSUE THREAD

**Issue by psociety** [metonym/svelte-typeahead#64]
Thank you for creating typeahead! It's really cool!

I would like to show the first entries when clicking the input, (like a select would do). It can be useful to avoid typing when the list is initially small.
I tought it was `showDropdownOnFocus` but it doesn't show up when input is empty :O

**Comment by metonym** [comment]
Thanks for raising this issue.

This is supported in [v4.4.0](https://github.com/metonym/svelte-typeahead/releases/tag/v4.4.0). Set `showAllResultsOnFocus` to `true` for all results to be shown when an empty input is focused.

```svelte
<Typeahead showAllResultsOnFocus {data} {extract} />
```

[Link to demo](https://metonym.github.io/svelte-typeahead/#show-all-results-on-focus)

**Comment by psociety** [comment]
[![N|Solid](https://media.tenor.com/mhhAGXRAUbYAAAAM/happy.gif)](https://media.tenor.com/mhhAGXRAUbYAAAAM/happy.gif)
